apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: HelmChartProxy
metadata:
  name: nginx-ingress-chart
spec:
  clusterSelector:
    key: nginxIngressChart
    value: enabled
  repoURL: https://helm.nginx.com/stable
  chartName: nginx-ingress
  values: |
    controller:
      name: "{{ .Cluster.Name }}-nginx"
