apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: metallb
spec:
  rollout:
    install:
      stepInit: 10%
      stepIncrement: 5%
      stepLimit: 25%
    upgrade:
      stepInit: 10%
      stepIncrement: 5%
      stepLimit: 25%
  clusterSelector:
    matchLabels:
      MetalLBChart: enabled
  repoURL: https://metallb.github.io/metallb
  chartName: metallb
  releaseName: metallb
