name: Weekly security scan

on:
  schedule:
    # Cron for every Monday at 12:00 UTC.
    - cron: "0 12 * * 1"
  workflow_dispatch:

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        branch: [ main ]
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # tag=v6.0.0
      with:
        ref: ${{ matrix.branch }}
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # tag=v5.5.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run verify security target
      run: make verify-security
